global using BlazorApp2.Server.Logic;
global using BlazorApp2.Server.WebService;
global using BlazorApp2.Shared.DAO;
global using BlazorApp2.Shared.Model;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.Data.SqlClient;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore;
global using System.Security.Claims;
global using System.Text.Json.Serialization;
global using System.Text.Json;
global using static BlazorApp2.Server.Logic.Values;