global using BlazorApp2.Client.Logic;
global using BlazorApp2.Client;
global using BlazorApp2.Shared.DAO;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.JSInterop;
global using System.Security.Claims;
global using System.Text.Json;
global using static BlazorApp2.Shared.Logic.SharedValues;